### ISSUE TITLE
Implement a pyproject.toml configuration block

### ISSUE THREAD

**Issue by nicholasjng** [aai-institute/nnbench#159]
In user code, we can easily instantiate a reporter etc. with arguments, but on the command line, this does not work. Therefore, we have to use a different idea.

One possibility is to use `pyproject.toml` as a configuration basis, with general information in the top-level `[tool.nnbench]` key, and more specific cases underneath:

```toml
[tool.nnbench]
log-level = "INFO"

[tool.nnbench.context]
providers = {
    "myctx" = "path.to.MyContextProviderClass"
} # to be used as `nnbench run benchmarks.py --context=provider=myctx`

[tool.nnbench.runner]
typecheck = true

[tool.nnbench.reporter]
# to be filled in, maybe options for custom classes here:
 myreporter = {
    class = "path.to.MyReporter", options = {...}
}

```
